# <b> $$\text{Quiz2} $$</b>
Let us consider a two dimensional array $M$ with entries as follows
<img src="Quiz22.png">

1. Write a python code to create the array $M$.

In [48]:
import numpy as np 

M =  np.array([[23,-3,7,1,22,20],[5,-6,70,9,-3,-2],[0,4,2.4,12,8,7],[2,10,-9,-4,5,20],[13,8,4,4,-2,5],[1,4,2,3,7,1]])

2. Write one line python code to slice the values of $M$ in the blue box.

In [47]:
M[:,2]

array([ 7. , 70. ,  2.4, -9. ,  4. ,  2. ])

3. Write one line python code to slice the values of $M$ in the red box.

In [28]:
M[0:1,3:5]

array([[ 1., 22.]])

4. Write one line python code to slice the values of $M$ in the green box.

In [29]:
M[4:6,4:6]

array([[-2.,  5.],
       [ 7.,  1.]])

5. Write one line python code to define an array $B$ with entries obtained by slicing the values of $M$ in the purple boxes.

In [38]:
B = M[2:5:2,0:5:2]

6. Write one line python code to display the shape of $B$.

In [39]:
B.shape

(2, 3)

7. Write one line python code to change of shape $B$.

In [44]:
B = B.reshape(3,2)

8. Write one line python code to display the new shape of the matrix $B$.

In [45]:
B.shape

(3, 2)

In [51]:
x = np.array([[0,1,3],[4,5,9],[7,2,9]])

In [52]:
x

array([[0, 1, 3],
       [4, 5, 9],
       [7, 2, 9]])

In [58]:
x[0:3:2,0:3:2]

array([[0, 3],
       [7, 9]])

In [61]:
x[0:2,0:2]

array([[0, 1],
       [4, 5]])

In [62]:
x[:,1]

array([1, 5, 2])

In [63]:
x[2,:]

array([7, 2, 9])

In [72]:
x[0:2:1,1:3:1]

array([[1, 3],
       [5, 9]])

In [70]:
x

array([[0, 1, 3],
       [4, 5, 9],
       [7, 2, 9]])

In [73]:
x[2,2]

9

In [78]:
m,n = x.shape
for i in range(0,n):
    print(x[i,:].sum())

4
18
18


In [79]:
m,n = x.shape
for i in range(0,n):
    print(x[:,i].sum())

11
8
21


In [83]:
x.sum(axis=0)

array([11,  8, 21])