In [1]:
import numpy as np


In [3]:
??np.arange

In [4]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [8]:
np.arange(1.0,20.0,0.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5,
       12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5, 17. ,
       17.5, 18. , 18.5, 19. , 19.5])

In [22]:
a=np.linspace(-10.0,10.0,30)

In [23]:
a

array([-10.        ,  -9.31034483,  -8.62068966,  -7.93103448,
        -7.24137931,  -6.55172414,  -5.86206897,  -5.17241379,
        -4.48275862,  -3.79310345,  -3.10344828,  -2.4137931 ,
        -1.72413793,  -1.03448276,  -0.34482759,   0.34482759,
         1.03448276,   1.72413793,   2.4137931 ,   3.10344828,
         3.79310345,   4.48275862,   5.17241379,   5.86206897,
         6.55172414,   7.24137931,   7.93103448,   8.62068966,
         9.31034483,  10.        ])

In [26]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [27]:
np.arange(1,2.25,0.25)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [32]:
n =  lambda a,b,dx: (b-a+dx)/dx

In [33]:
n(-1,4,0.5)

11.0

In [31]:
np.linspace(-1,4,9)

array([-1.   , -0.375,  0.25 ,  0.875,  1.5  ,  2.125,  2.75 ,  3.375,
        4.   ])

In [34]:
np.__version__

'1.17.3'

define a function that takes input $(a,b,n,q)$  $ \int_{a}^{b} f(n) \,dx  $