In [4]:
import scipy as sp
import numpy as np

In [28]:
x = np.random.randn(4,3)
x

array([[-1.72758064, -0.38618006,  0.35002765],
       [ 1.09440708,  1.90188587,  0.25618076],
       [-0.87726355,  1.19451906, -0.86748616],
       [-0.42972641,  0.30045188,  0.79692928]])

In [29]:
np.ndim(x)

2

In [30]:
np.shape(x)

(4, 3)

In [31]:
np.size(x)

12

In [21]:
t = np.random.randn(10,14,3)

In [22]:
t

array([[[ 0.49130422,  1.59044648,  0.562633  ],
        [ 1.74354091, -0.37782677,  1.60709876],
        [ 0.02151636,  0.4676919 , -1.45484169],
        [-0.18595522,  1.10124771, -0.70026019],
        [-0.16423838,  0.54579717, -0.68701501],
        [ 1.40500697, -0.35852928, -0.82876964],
        [-1.02858069, -0.71215131,  0.65630563],
        [-1.99834463,  0.54630648,  0.12566662],
        [-0.48245545,  0.21706208, -1.7045104 ],
        [-0.21555599, -0.21246566,  0.04473077],
        [-1.02764862,  1.28519236, -0.05290058],
        [-0.47141216,  0.62276551,  0.22807158],
        [-0.26178858,  0.0805043 , -0.3753017 ],
        [-1.69097435, -0.31265274, -0.70907875]],

       [[-1.05814652, -0.0314793 , -0.73052999],
        [-0.44523573,  0.5846781 , -0.54817833],
        [ 0.92763468,  1.45142663, -0.91187382],
        [ 0.66121869,  0.91219334,  0.26006573],
        [ 0.35883382,  0.16565476,  0.28345253],
        [ 1.94996316, -0.35032048, -0.9462597 ],
        [-1.526401

In [23]:
np.ndim(t)

3

In [24]:
np.size(t)

420

In [25]:
t

array([[[ 0.49130422,  1.59044648,  0.562633  ],
        [ 1.74354091, -0.37782677,  1.60709876],
        [ 0.02151636,  0.4676919 , -1.45484169],
        [-0.18595522,  1.10124771, -0.70026019],
        [-0.16423838,  0.54579717, -0.68701501],
        [ 1.40500697, -0.35852928, -0.82876964],
        [-1.02858069, -0.71215131,  0.65630563],
        [-1.99834463,  0.54630648,  0.12566662],
        [-0.48245545,  0.21706208, -1.7045104 ],
        [-0.21555599, -0.21246566,  0.04473077],
        [-1.02764862,  1.28519236, -0.05290058],
        [-0.47141216,  0.62276551,  0.22807158],
        [-0.26178858,  0.0805043 , -0.3753017 ],
        [-1.69097435, -0.31265274, -0.70907875]],

       [[-1.05814652, -0.0314793 , -0.73052999],
        [-0.44523573,  0.5846781 , -0.54817833],
        [ 0.92763468,  1.45142663, -0.91187382],
        [ 0.66121869,  0.91219334,  0.26006573],
        [ 0.35883382,  0.16565476,  0.28345253],
        [ 1.94996316, -0.35032048, -0.9462597 ],
        [-1.526401

In [32]:
M =  np.zeros((10,10))

In [33]:
p = np.array([[2,-1,0,0],[0,2,-1,0],[0,-1,2,-1]])

In [34]:
p

array([[ 2, -1,  0,  0],
       [ 0,  2, -1,  0],
       [ 0, -1,  2, -1]])

In [40]:
M[0:3:1,0:4:1] = p

In [39]:
p.shape

(3, 4)

In [44]:
M[9,8] = -1

In [45]:
M

array([[ 2., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  2., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0., -1.,  2., -1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  2.]])

In [49]:
M =  np.zeros((10,10))
for i in range(10):
    for j in range(10):
        if i == j:
            M[i,j] = 2
        elif abs(j-i) == -1:
            M[i,j] = -1

In [50]:
M

array([[2., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 2., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 2., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 2., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 2., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 2., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 2., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 2., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 2.]])

In [68]:
M =  np.zeros((10,10))
for i in range(10):
    for j in range(10):
        if i == j:
            M[i,j] = 2
        elif (j == i-1):
            M[i,j] = 1
        elif (j == i+1):
            M[i,j] = -1

In [66]:
M

array([[ 2., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  2., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  2., -1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  2., -1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  2., -1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  2., -1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  2., -1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  2., -1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  2., -1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  2.]])

In [53]:
np.abs(-10)

10

In [69]:
R =  np.array([[1,3],[-1,7]])

S = np.array([[5,2],[1,2]])

In [70]:
R

array([[ 1,  3],
       [-1,  7]])

In [71]:
S

array([[5, 2],
       [1, 2]])

In [75]:
I = np.diag([1,1])

In [76]:
I

array([[1, 0],
       [0, 1]])

In [77]:
2*I + 4*R + R*S

array([[11, 18],
       [-5, 44]])

In [79]:
R@S

array([[ 8,  8],
       [ 2, 12]])

In [80]:
R*S

array([[ 5,  6],
       [-1, 14]])

In [135]:
import numpy as np
def SeqTerms(n):
    U =  np.zeros((n,1))
    U[0] = 1
    U[1] = 2
    U[2] = 3
    if(n == 0):
        return np.array([])
    elif (n ==1):
        return C[:n]
    else:
        for i in range(3,n):
            U[i] = U[i-1] - 3*U[i-2] + U[i-3] 
        return U


In [136]:
SeqTerms(10)

array([[  1.],
       [  2.],
       [  3.],
       [ -2.],
       [ -9.],
       [  0.],
       [ 25.],
       [ 16.],
       [-59.],
       [-82.]])

In [126]:
C =  np.zeros((5,))

In [127]:
C

array([0., 0., 0., 0., 0.])

In [116]:
C[0,4] = 10

In [118]:
C[0:,:2]

array([[0., 0.]])

In [138]:
x =  np.arange(20).reshape(4,5)

In [139]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [140]:
np.trace(x)

36