In [2]:
import numpy as np

In [2]:
arr = np.array(42)

arr

array(42)

In [3]:
type(arr)

numpy.ndarray

In [3]:
m =  np.array([[1,2],[3,4]])

In [4]:
m

array([[1, 2],
       [3, 4]])

In [5]:
m.shape

(2, 2)

In [10]:
x  = np.linspace(0,1,21)

In [12]:
x.shape = 3,7

In [13]:
x.shape

(3, 7)

In [14]:
x

array([[0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 ],
       [0.35, 0.4 , 0.45, 0.5 , 0.55, 0.6 , 0.65],
       [0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ]])

In [15]:
100 * 9999

999900

In [16]:
y = np.linspace(-100,100,999900)

In [17]:
y.shape

(999900,)

In [19]:
y.shape = 100,9999

In [20]:
y

array([[-100.        ,  -99.99979998,  -99.99959996, ...,  -98.00059806,
         -98.00039804,  -98.00019802],
       [ -97.999998  ,  -97.99979798,  -97.99959796, ...,  -96.00059606,
         -96.00039604,  -96.00019602],
       [ -95.999996  ,  -95.99979598,  -95.99959596, ...,  -94.00059406,
         -94.00039404,  -94.00019402],
       ...,
       [  94.00019402,   94.00039404,   94.00059406, ...,   95.99959596,
          95.99979598,   95.999996  ],
       [  96.00019602,   96.00039604,   96.00059606, ...,   97.99959796,
          97.99979798,   97.999998  ],
       [  98.00019802,   98.00039804,   98.00059806, ...,   99.99959996,
          99.99979998,  100.        ]])

In [23]:
x = np.arange(9).reshape(3,3)

In [24]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
x[1:3]

array([[3, 4, 5],
       [6, 7, 8]])

In [29]:
x[1::]

array([[3, 4, 5],
       [6, 7, 8]])

In [33]:
x[0:2:1]

array([[0, 1, 2],
       [3, 4, 5]])

In [37]:
x[2:3:4]

array([[6, 7, 8]])

In [39]:
x = np.arange(9).reshape(3,3)


In [40]:
x[:,0]

array([0, 3, 6])

In [41]:
x


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [42]:
x[0,:]

array([0, 1, 2])

In [43]:
x[1,:]

array([3, 4, 5])

In [44]:
x[1:3]

array([[3, 4, 5],
       [6, 7, 8]])

In [45]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [46]:
x[0:3]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
x[:,1:]

array([[1, 2],
       [4, 5],
       [7, 8]])

array([], shape=(3, 0), dtype=int64)