In [15]:
import numpy as np

In [1]:
# Tuple unpacking
lst = [(1,2),(3,4),(5,6)]


In [3]:
for (a,b) in lst:
    print(a," ",b)

1   2
3   4
5   6


In [13]:
# list comprehension

x  =  list(range(5))

y = [ k**2 for k in x]

In [14]:
y

[0, 1, 4, 9, 16]

In [16]:
my_list = [[1,2,3],[4,5,6],[7,8,9]]


In [17]:
my_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [18]:
np.array(my_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
# np.arange takes 3 arguments start, stop (exclusive) and step
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
# np.linspace takes 3 arguments start, stop  and size
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [36]:
# np.zeros takes  a parameter as the shape of the object, 1 parameter indicates a vector 
# and 2 indicate a matrix
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
# np.ones takes  a parameter as the shape of the object, 1 parameter indicates a vector 
# and 2 indicate a matrix
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [38]:
# np.eye creates an identity matrix where the parametr indicates the size of the matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
# Generating an array of random numbers from a uniform distribution
np.random.rand(4,3)

array([[0.7430233 , 0.76695239, 0.55701774],
       [0.19025175, 0.18951666, 0.54036676],
       [0.58137425, 0.0339224 , 0.33000368],
       [0.47670966, 0.11757565, 0.53149939]])

In [29]:
# Generating an array of random numbers from a normal distribution
np.random.randn(4,3)

array([[-0.54073644, -1.00242084,  0.52510221],
       [-2.54877155, -0.99706599,  1.38351212],
       [ 1.19905683,  0.63237886,  1.56705822],
       [-0.1139968 ,  0.71597909, -0.3769431 ]])

In [33]:
# Generating an array of random integers from low to high and size
np.random.randint(1,100,50)

array([70, 86, 74, 45, 80,  8, 67, 71, 49, 85, 23,  7, 14, 61, 47, 67, 32,
       47, 60, 12, 94, 42, 57, 16, 23, 23,  5, 38, 42, 43,  9,  7, 87, 57,
       99, 69, 32, 50, 71, 94,  7, 19,  7, 14, 79, 44, 43, 76, 64, 96])

In [42]:
# using the reshape method for arrays

arr = np.arange(25)

# Method 1
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
# Method 2

arr.shape = 5,5
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
arra =  np.random.randint(1,100,50)
arra

array([20, 30, 63, 37,  7,  6, 57, 75, 93, 59, 91, 98, 44,  9, 20, 54, 38,
        6, 63, 30, 93, 84, 34, 59, 10, 63, 37, 73, 76, 40, 72, 92,  2, 10,
       87, 55, 70, 88,  5, 68, 29, 45, 21,  3, 40, 96,  6, 46, 21, 29])

In [60]:
# max method

arra.max()

# using the index of the max
arra[arra.argmax()]

98

In [56]:
# argmax

arra.argmax()

11

In [59]:
# min method

arra.min()

# using the index of the min

arra[arra.argmin()]

2

In [57]:
# argmin

arra.argmin()

32

In [61]:
# figuring out the shape an array

arra.shape

(50,)

In [64]:
# we are reshaping and getting the new shape at a go, pretty nifty :)
arra.reshape(10,5).shape

(10, 5)

In [65]:
# every wondered how to know the datatype of an array object, here is it

arra.dtype

dtype('int64')

### Indexing and selection

In [66]:
arr =  np.arange(0,11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
arr[0]

0

In [68]:
arr[0:4]

array([0, 1, 2, 3])

In [69]:
# using the indexing notation 0 as start 8 as stop and 2 as step
arr[0:8:2]

array([0, 2, 4, 6])

In [81]:
# using the reverse indexing notation -11 as start -1 as stop and 2 as step
arr[-11:-1:2]

array([0, 2, 4, 6, 8])

In [82]:
# start from index 4 and get me everything after it
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [84]:
# start from index 0 up to but not including index 4
arr[:4]

array([0, 1, 2, 3])

### 2D slicing

In [90]:
arr =  np.random.randn(4,3)
arr

array([[-0.63824805, -0.02651148, -0.62538292],
       [-2.03164115,  0.35839649,  0.30836007],
       [-1.53571002, -0.07558944, -0.19796806],
       [-0.57641544, -1.14470358, -1.6555468 ]])

In [88]:
# Row 0 column 0
arr[0][0]

-0.19949797038573677

In [89]:
# Row 0 every column

arr[0,:]

array([-0.19949797, -0.44881396,  0.18110698])

In [91]:
# Column 0 every row

arr[:,0]

array([-0.63824805, -2.03164115, -1.53571002, -0.57641544])

In [92]:
# Row 0 to 2 and column 0 to 2
arr[0:2,0:2]

array([[-0.63824805, -0.02651148],
       [-2.03164115,  0.35839649]])

In [93]:
# boolean arrays

bool_arr =  arr >0.1

In [95]:
arr[bool_arr]

array([0.35839649, 0.30836007])

In [96]:
# Conditional selection one-liner

arr[arr > 0.1]

array([0.35839649, 0.30836007])

### Array Operations

In [99]:
arr = np.arange(0,11)


In [101]:
# Scalar addition
arr +1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [102]:
# Scalar multiplication
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [103]:
# vector addition
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [104]:
# Vector multiplication
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [108]:
# vector division
arr[0] = 1
arr /  arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [109]:
# vector subtraction
arr -  arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [112]:
# matrix addition
arr2 =  np.random.randint(1,100,20).reshape(5,4)
arr2

array([[74, 35, 53, 33],
       [22, 75, 41, 62],
       [11, 23, 72, 30],
       [ 2, 83,  7, 94],
       [16, 91, 61, 44]])

In [114]:
# matrix scalar addition
arr2 + 1

array([[75, 36, 54, 34],
       [23, 76, 42, 63],
       [12, 24, 73, 31],
       [ 3, 84,  8, 95],
       [17, 92, 62, 45]])

In [115]:
# matrix scalar multiplication
arr2 + 2

array([[76, 37, 55, 35],
       [24, 77, 43, 64],
       [13, 25, 74, 32],
       [ 4, 85,  9, 96],
       [18, 93, 63, 46]])

In [116]:
# matrix scalar subtraction
arr2 -10

array([[64, 25, 43, 23],
       [12, 65, 31, 52],
       [ 1, 13, 62, 20],
       [-8, 73, -3, 84],
       [ 6, 81, 51, 34]])

In [117]:
# matrix scalar division
arr2 / 2

array([[37. , 17.5, 26.5, 16.5],
       [11. , 37.5, 20.5, 31. ],
       [ 5.5, 11.5, 36. , 15. ],
       [ 1. , 41.5,  3.5, 47. ],
       [ 8. , 45.5, 30.5, 22. ]])

In [121]:
arr =  np.arange(1,6)
arr

array([1, 2, 3, 4, 5])

In [128]:
# matrix vector addition
arr  @ arr2

array([ 239, 1041,  684,  843])

In [124]:
arr.shape

(5,)

In [125]:
arr2.shape

(5, 4)

In [136]:
# numpy universal functions
arr =  np.linspace(0,10,20)
np.sin(arr)

array([ 0.        ,  0.50235115,  0.86872962,  0.99996678,  0.86054034,
        0.48818921, -0.01630136, -0.5163796 , -0.87668803, -0.99970104,
       -0.85212237, -0.47389753,  0.03259839,  0.53027082,  0.88441346,
        0.99916962,  0.84347795,  0.4594799 , -0.04888676, -0.54402111])

In [130]:
np.cos(arr)

array([ 1.        ,  0.8646637 ,  0.49528663, -0.00815095, -0.5093823 ,
       -0.87273782, -0.99986712, -0.8563598 , -0.48105935,  0.02445069,
        0.52334259,  0.88058   ,  0.99946853,  0.84782832,  0.46670422,
       -0.04074393, -0.53716381, -0.88818817, -0.99880433, -0.83907153])

In [131]:
np.tan(arr)

array([ 0.00000000e+00,  5.80978655e-01,  1.75399366e+00, -1.22680990e+02,
       -1.68938014e+00, -5.59376710e-01,  1.63035275e-02,  6.02993740e-01,
        1.82241138e+00, -4.08864175e+01, -1.62823049e+00, -5.38165216e-01,
        3.26157245e-02,  6.25445980e-01,  1.89501922e+00, -2.45231548e+01,
       -1.57024344e+00, -5.17322704e-01,  4.89452788e-02,  6.48360827e-01])

In [132]:
np.cosh(arr)

array([1.00000000e+00, 1.14173106e+00, 1.60709961e+00, 2.52802002e+00,
       4.16553834e+00, 6.98382895e+00, 1.17817705e+01, 1.99193976e+01,
       3.37034193e+01, 5.70410834e+01, 9.65477336e+01, 1.63422009e+02,
       2.76620232e+02, 4.68229810e+02, 7.92564801e+02, 1.34156189e+03,
       2.27084094e+03, 3.84381737e+03, 6.50637039e+03, 1.10132329e+04])

In [133]:
np.tanh(arr)

array([0.        , 0.48255983, 0.78282736, 0.91843734, 0.97075681,
       0.98969552, 0.99639145, 0.99873907, 0.99955973, 0.99984632,
       0.99994636, 0.99998128, 0.99999347, 0.99999772, 0.9999992 ,
       0.99999972, 0.9999999 , 0.99999997, 0.99999999, 1.        ])

In [134]:
np.sinh(arr)

array([0.00000000e+00, 5.50953543e-01, 1.25808154e+00, 2.32182800e+00,
       4.04372472e+00, 6.91186421e+00, 1.17392553e+01, 1.98942806e+01,
       3.36885807e+01, 5.70323171e+01, 9.65425547e+01, 1.63418949e+02,
       2.76618424e+02, 4.68228742e+02, 7.92564170e+02, 1.34156151e+03,
       2.27084072e+03, 3.84381724e+03, 6.50637031e+03, 1.10132329e+04])

In [135]:
np.log(arr)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([       -inf, -0.64185389,  0.05129329,  0.4567584 ,  0.74444047,
        0.96758403,  1.14990558,  1.30405626,  1.43758766,  1.55537069,
        1.66073121,  1.75604139,  1.84305276,  1.92309547,  1.99720344,
        2.06619631,  2.13073484,  2.19135946,  2.24851787,  2.30258509])

In [137]:
np.exp(arr)

array([1.00000000e+00, 1.69268460e+00, 2.86518116e+00, 4.84984802e+00,
       8.20926306e+00, 1.38956932e+01, 2.35210258e+01, 3.98136782e+01,
       6.73920000e+01, 1.14073401e+02, 1.93090288e+02, 3.26840958e+02,
       5.53238656e+02, 9.36458553e+02, 1.58512897e+03, 2.68312340e+03,
       4.54168166e+03, 7.68763460e+03, 1.30127407e+04, 2.20264658e+04])

In [138]:
np.std(arr)

3.03488489333442

In [139]:
np.mean(arr)

5.0

In [140]:
np.var(arr)

9.210526315789474

In [146]:
np.std(np.random.randn(10000))

1.002916258281654

In [148]:
arr2.sum(axis=0)

array([125, 307, 234, 263])

In [149]:
arr2.sum(axis=1)

array([195, 200, 136, 186, 212])

In [153]:
arr2.argmax(axis=0)

array([0, 4, 2, 3])

In [156]:
arr2.max(axis=0)

array([74, 91, 72, 94])