In [1]:
import numpy as np

In [14]:
A  =  np.array([[2,3],[2,1]])

np.linalg.matrix_power(A,5)

array([[614, 615],
       [410, 409]])

In [5]:
A**5

array([[ 32, 243],
       [ 32,   1]])

In [6]:
P =  np.array([[3,-1],[2,1]])
P

array([[ 3, -1],
       [ 2,  1]])

In [12]:
D = np.array([[4**5,0],[0,-1**5]])
D

array([[1024,    0],
       [   0,   -1]])

In [13]:
P@D@np.linalg.inv(P)

array([[614., 615.],
       [410., 409.]])

In [16]:
P =  np.array([[-3,-1],[2,1]])
P

array([[-3, -1],
       [ 2,  1]])

In [17]:
np.linalg.inv(P)

array([[-1., -1.],
       [ 2.,  3.]])

In [19]:
D =  np.array([[1,0],[0,0.5]])