In [1]:
import numpy as np

In [8]:
def self_attention(K,Q,V):
    A  = np.exp(K@Q.T)/np.sqrt(K.shape[1])
    return (A  /  np.sum(A,1))@V

In [12]:
K,Q,V = np.random.randn(3,4,5)
print(self_attention(K,Q,V))

[[ 0.32316669 -3.67421136  1.4249636   1.96593528  1.21523354]
 [ 0.13181549 -0.56031142  0.21530786 -0.0342245   0.34551909]
 [ 0.70653685 -9.5905569  -1.65473757 -0.82303087  9.41329508]
 [ 0.12913985 -0.78164281  0.34005027  0.25071845  0.29910221]]
